### ISSUE TITLE
[BUG] Autoalpha does not unhide slices upon detach

### ISSUE THREAD

**Issue by Amanda-Desire** [wokes/Meshbody#1]
**Describe the bug**
Autoalpha failed to restore slices after removal of clothing.

**To Reproduce**

1. Go to Fameshed fair. 
http://maps.secondlife.com/secondlife/FaMESHed/223/251/800
2. Demo Ricielli Bee Outfit.
3. Wear red dress and jacket.
4. Remove dress and jacket.
5. Body does not realpha arms

**Expected behavior**
Removal of the jacket should have restored the alpha on my arms that the jacket had auto applied.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://gyazo.com/2e561aff7ec534cd3eebb42cdebc067b)

**Product (please complete the following information):**
 - Name: Legacy Tester
 - Version 3/3/23 - Feminine

**Additional context**

**Comment by Amanda-Desire** [comment]
Bug confirmed again with another outfit. Alpha slices no not reappear. Might be because I wore a new outfit before taking the old one off.

1. Wear Scandalize Famele Set Top and bottom magapack
2. Wear -Pixicat- Juliette Dress - Latex
3. Remove top and bottom of Scandalize set
4. 4Slides are not removed from Scandalize set

Expected behavior: Slices should remove from first worn outfit.

https://gyazo.com/66203367a6e520f5cdfc6453bbbc5838

**Comment by wokes** [comment]
Notes:
The Ricielli dress is a non-factor, it does not contain an alpha applier.

**Comment by wokes** [comment]
Attempt was made to patch, it could take up to 10 seconds for the backup method to detect detachment.
