### ISSUE TITLE
[BUG] Nail hides on themselves

### ISSUE THREAD

**Issue by FreyaIthildur** [wokes/Meshbody#10]
### Reported by idixinfernal

**Describe the bug**
_Telporting around into the same parcel made the fingernails on one hand disappear. They can be shown againb only with chat command (original report)_

**NEW!!!**
Issue showing on teleporting is a consequence of alpha refresh: in reality the nails of fingers and toes hide regardless through the hiding of hands and feet through the EDIT hud. Only way to show them back up is using the chat commands

**To Reproduce**
_1. Hide the toe nails by command 
2. Tp to 3 different regions (2951m-4095m-ground) the nails on Right Hand get hidden by itself (original report)_

**NEW!!!**
1. Add the EDIT HUD
2. Hide your Hands and feet from Fit section.
3. Unhide them

**Expected behavior**
Fingernails and Toenails should appear again upon alpha unhide. 

**Screenshots**
https://i.gyazo.com/7cf5965b630309bda83e65b4fe51fce3.png

**Product (please complete the following information):**
 - Name: TESTER 3/3/23 - Masculine
 - Version 1.5.1

**Additional context**

**Comment by FreyaIthildur** [comment]
### from idixinfernal
March 23rd

6. Finger Nails disappear on Alpha
• On previous report, it was single hand only while tp. Apparently it's also happened when you alpha the hands.
    a. EDIT HUD is irresponsive to bring back the nails
    b. Nails only appear by command
• https://i.gyazo.com/8b1f3104969256f6a3a2cae438fb380b.mp4
• https://i.gyazo.com/07a5358601e2cca93cc3e245055e9eb2.mp4

**Comment by FreyaIthildur** [comment]
@wokes updated the original issue here with new information to reproduce the issue, it's confirmed

**Comment by Collaboratives** [comment]
duplicate https://github.com/Collaboratives/MeshbodyBugReports/issues/15
