### ISSUE TITLE
Ankle Locks Breaks[BUG]

### ISSUE THREAD

**Issue by Amanda-Desire** [wokes/Meshbody#2]
**Describe the bug**
When switching between certain animations on furniture, the ankle lock breaks. This may be a priority issue, or because the Legacy HUD ankle lock does not periodically refire like some others on the market to refresh itself. 

**To Reproduce**
1. Activate Ankle Lock before or after sitting on BackBone Sensual Massage - Table
2. Select Massage->More for Her->Right Thigh, ankle lock works.
3. Now Select Massage->Massage her->Whole Body, ankle lock breaks.

**Expected behavior**
The best ankle locks seem to look for issues like this and retrigger the lock on a timer. I know if an SL anim has the same priority as the lock, it will override it if it is the "newer" anim of the same  priority. We do a lot of dance and having a reliable ankle lock is important for burlesque performance shows.

**Screenshots**

See meta tags for the poses that broke the lock:

https://gyazo.com/3392d922677007ffb668c93dd9b15b32
https://gyazo.com/445d645b9f64fe38ad0695d07b740bc5

**Product (please complete the following information):**
 - Name: Legacy tester body
 - Version 3/3/23

**Additional context**

**Comment by Amanda-Desire** [comment]
Another idea..what is the priority level of the ankle lock anim? The highest that can be exported is 6. Most anims in SL furniture are 4 or 2. A priority 6 ankle lock anim might work for nearly all cases without the need for a timer.

**Comment by FreyaIthildur** [comment]
> Another idea..what is the priority level of the ankle lock anim? The highest that can be exported is 6. Most anims in SL furniture are 4 or 2. A priority 6 ankle lock anim might work for nearly all cases without the need for a timer.

Actual priority should be 5 for ankle locks AFAIK

**Comment by Amanda-Desire** [comment]
Didn't know there was a convention to it being Priority 5. But it is possible to do 6 and that might avoid having to add a timer that refires the ankle lock anim. I'll test with the ankle lock we use for dance and see if I can reproduce it on that.

**Comment by Amanda-Desire** [comment]
Priority 6 anim by itself did not fix the issue. What worked was setting a timer and checking for the anklelock animation playing and then retriggering the anim if the anklelock anim was no longer playing:

    timer(){        
        if (llListFindList( llGetAnimationList(llGetOwner()), [anim_uuid] ) == -1){ // if anim isn't playing
            llStartAnimation(anim_name);
        }
    }

Timer is not ideal, but might be another way to fix it.

**Comment by wokes** [comment]
Attempt was made to patch, it could take up to 8 seconds for the backup method to restart the animation.
