### ISSUE TITLE
[BUG] Wearing export slices brings up Rigged Mesh on HUD warning.

### ISSUE THREAD

**Issue by Amanda-Desire** [wokes/Meshbody#7]
**Describe the bug**
After exporting a custom alpha slice prim, wearing that prim triggers Firestorm's "You are wearing rigged mesh on your HUD" warning.

**To Reproduce**
1. Alpha some slices on your body.
2. Export via hud to rez prim, name it, pick it up.
3. Wear the prim with "add" and you will get the rigged mesh warning.

**Expected behavior**
The export prim should be a prim instead of rigged mesh and not trigger such a warning?

**Screenshots**
https://gyazo.com/066367c5646a559140a4ca4493e57960

**Product (please complete the following information):**
 - Name: Legacy TESTER Feminine
 - Version 3/3/23

**Additional context**

**Comment by FreyaIthildur** [comment]
That is normal behaviour, no bug is working as intended 🙂

Viewer detects that you are wearing a rigged mesh item on your HUD instead than the body and is telling you a warning to inform you that you might be wearing a mesh item that is rigged to your body erroneously on your HUD instead

Wearing it on the HUD makes for a lower final complexity of your avatar as it hasn't to be rendered by other people
