### ISSUE TITLE
[BUG] Nails do not reappear

### ISSUE THREAD

**Issue by Amanda-Desire** [wokes/Meshbody#8]
**Describe the bug**
Soon after I got my new tester body, I wore it and put on some mesh Blaxium Aura Nails 2. I hid the Legacy nails, and would tp around and everything seemed fine. Only after a few weeks did I notice I could no longer turn on the legacy nails at all. Not even after relogging, refreshing attachments, or resetting the body via HUD, or switching between BoM and non BoM. 

Unfortunately, since I do not have a fresh copy of the tester body, I am unable to reproduce or find steps. I would like a new copy so that I can try to reproduce this. 

**To Reproduce**

1. Already be wearing the Blaxium Aura Nails 2 before you put on the tester.
2. Wear the tester body, hands, feet, HUD.
4. Turn off the legacy nails.
5. Tp around a bit.
6. Try to turn on Legacy nails without removing Blaxium. No nails appear.
7. Remove Blaxium and attempt to activate legacy nails. try resetting, try bom switch, try refreshing attachments, try relogging. Nails do not come back.

**Expected behavior**
legacy nails should  always turn back on when using the HUD. Sorry I am unable to test further. Need fresh copy of tester body to confirm steps.

**Screenshots**
https://gyazo.com/ce73ad65184ca424a11534ebaca5c4f1

**Product (please complete the following information):**
 - Name: [e.g. Legacy Perky]
 - Version [e.g. 1.4]

**Additional context**

**Comment by Amanda-Desire** [comment]
Detaching the HUD and body, wearing something else (like another rigged body, non legacy), and then wearing the tester again seems to fix the nail issue. Will try to repro the bug now.

**Comment by wokes** [comment]
> Detaching the HUD and body, wearing something else (like another rigged body, non legacy), and then wearing the tester again seems to fix the nail issue. Will try to repro the bug now.

@Amanda-Desire did you manage to reproduce the issue again?

**Comment by Amanda-Desire** [comment]
I was not able to repro. I will keep trying.

**Comment by Collaboratives** [comment]
duplicate issue #15
